### ISSUE TITLE
Attribute Error unittouu

### ISSUE THREAD

**Issue by jjdejong** [cds4/inkscape-grids#1] opened 2016-11-18 08:08 UTC
I installed these in Inkscape 0.91 for Mac. I systematically get this message:

Traceback (most recent call last):
  File "grid_perspect2.py", line 304, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()
  File "grid_perspect2.py", line 181, in effect
    self.ymax = inkex.unittouu(str(self.options.height)+self.options.size_unit)
AttributeError: 'module' object has no attribute 'unittouu'

**Comment by cds4** [comment] 2016-11-18 23:54
I have now fixed this problem, which was caused by a change in Inkscape 0.91.

The new version has been tested to work.

Thanks for the report.

Carl

**Closed as completed by cds4** 2016-11-18 23:54 UTC
